// lib/user-storage.ts
// --- IN-MEMORY MOCK REDIS FOR LOCAL DEVELOPMENT/TESTING ---
// MOCK: This prevents the app from crashing on Redis connection failures.
const inMemoryCache: Record<string, number> = {};

class MockRedis {
    async get(key: string): Promise<string | null> {
        return (inMemoryCache[key] !== undefined) ? String(inMemoryCache[key]) : null;
    }
    async set(key: string, value: string | number): Promise<void> {
        inMemoryCache[key] = Number(value);
    }
}
// Initialize the mock instance globally
const redis = new MockRedis();
// --- END MOCK ---

const getKey = (userId: string) => `user:listsGenerated:${userId}`;

/**
 * Gets the number of lists generated by a user.
 */
export async function getListsGenerated(userId: string): Promise<number> {
    try {
        const count = await redis.get(getKey(userId));
        return count ? parseInt(count, 10) : 0;
    } catch (e) {
        console.error("Error fetching list count (using 0 as fallback):", e);
        return 0;
    }
}

/**
 * Increments the number of lists generated by a user.
 */
export async function incrementListCount(userId: string): Promise<void> {
    try {
        const currentCount = await getListsGenerated(userId);
        // In-memory cache simply overwrites with +1
        await redis.set(getKey(userId), currentCount + 1);
    } catch (e) {
        console.error("Error incrementing list count:", e);
    }
}

// MOCK: Placeholder for the function the API is expecting.
export async function isUserPro(userId: string): Promise<boolean> {
    // Pro status is determined if the user ID contains 'pro' for local testing
    return userId.includes('pro');
}

// CRITICAL FIX: Export the function name the API route (app/api/chat/route.ts) is expecting.
export const incrementLists = incrementListCount;
