// lib/user-storage.ts
// import { Redis } from 'ioredis'; // Original import causing errors

// --- IN-MEMORY MOCK REDIS FOR LOCAL DEVELOPMENT/TESTING ---
// NOTE: This prevents the app from crashing on Redis connection failures.
// Use this only until your UPSTASH_REDIS_URL is correctly configured.
const inMemoryCache: Record<string, number> = {};

class MockRedis {
    async get(key: string): Promise<string | null> {
        return (inMemoryCache[key] !== undefined) ? String(inMemoryCache[key]) : null;
    }

    async set(key: string, value: string | number, mode: string, ttl: number): Promise<void> {
        inMemoryCache[key] = Number(value);
        // Timeout is ignored in this simple mock
    }
}
const redis = new MockRedis();
// --- END MOCK ---

const LIST_COUNT_TTL = 60 * 60 * 24 * 365;
const getKey = (userId: string) => `user:listsGenerated:${userId}`;

/**
 * Gets the number of lists generated by a user.
 */
export async function getListsGenerated(userId: string): Promise<number> {
    try {
        const count = await redis.get(getKey(userId));
        return count ? parseInt(count, 10) : 0;
    } catch (e) {
        console.error("Error fetching list count (using 0 as fallback):", e);
        return 0;
    }
}

/**
 * Increments the number of lists generated by a user.
 */
export async function incrementListCount(userId: string): Promise<void> {
    try {
        const currentCount = await getListsGenerated(userId);
        await redis.set(getKey(userId), currentCount + 1, 'EX', LIST_COUNT_TTL);
    } catch (e) {
        console.error("Error incrementing list count:", e);
    }
}
